%YAML 1.2
---
# ______ ______              _____
# ___  //_/__(_)________________(_)_____________ _____________
# __  ,<  __  /__  ___/_  ___/_  /__  __ \_  __ `/  _ \_  ___/
# _  /| | _  / _(__  )_(__  )_  / _  / / /  /_/ //  __/  /
# /_/ |_| /_/  /____/ /____/ /_/  /_/ /_/_\__, / \___//_/
#                                        /____/

#
# Now we are ready to set up Kissinger
#


#  /$$$$$$$$        /$$
# |__  $$__/       | $$
#    | $$  /$$$$$$ | $$  /$$$$$$   /$$$$$$   /$$$$$$  /$$$$$$  /$$$$$$/$$$$
#    | $$ /$$__  $$| $$ /$$__  $$ /$$__  $$ /$$__  $$|____  $$| $$_  $$_  $$
#    | $$| $$$$$$$$| $$| $$$$$$$$| $$  \ $$| $$  \__/ /$$$$$$$| $$ \ $$ \ $$
#    | $$| $$_____/| $$| $$_____/| $$  | $$| $$      /$$__  $$| $$ | $$ | $$
#    | $$|  $$$$$$$| $$|  $$$$$$$|  $$$$$$$| $$     |  $$$$$$$| $$ | $$ | $$
#    |__/ \_______/|__/ \_______/ \____  $$|__/      \_______/|__/ |__/ |__/
#                                 /$$  \ $$
#                                |  $$$$$$/
#                                 \______/
#

#
# Set here token for your telegram bot
# Use @Botfather bot in Telegram to create new one and get more instructions
TOKEN:

#
# We're finished setting up Kissinger
# Now it's ready to deploy
#