%YAML 1.2
---
# ______ ______              _____
# ___  //_/__(_)________________(_)_____________ _____________
# __  ,<  __  /__  ___/_  ___/_  /__  __ \_  __ `/  _ \_  ___/
# _  /| | _  / _(__  )_(__  )_  / _  / / /  /_/ //  __/  /
# /_/ |_| /_/  /____/ /____/ /_/  /_/ /_/_\__, / \___//_/
#                                        /____/
#                         Modern Telegram bot for kispython.ru

#
# Now we are ready to set up Kissinger
#

#
# Set here token for your telegram bot
# Use @Botfather bot in Telegram to create new one and get more instructions
TGTOKEN:

#
# Set here domain with DTA instance
# Don't forget about protocol (http/https) and leave it with slash in the end
URL: http://kispython.ru/api/v1/

#
# Set here your DTA access_token
# If you don't have one, i will use headless browser
DTATOKEN:

#
# Set here your SQLite database path
SQLITE: sqlite:///kissinger.sqlite

#
# We're finished setting up Kissinger
# Now it's ready to deploy